In [1]:
import re
import ast
import pandas as pd

In [2]:
# Function to safely convert stringified lists to lists and handle NaN values
def safe_literal_eval(s):
    try:
        if pd.isna(s):  # Check if the value is NaN
            return []  # Return an empty list for NaN values
        return ast.literal_eval(s)  # Convert string to list
    except ValueError:
        return []  # Return an empty list in case of parsing error

In [3]:
# Load the Pok√©mon dataset
pokemon_df = pd.read_csv('pokemon_go_data.csv')

In [4]:
# Apply safe_literal_eval to 'Fast Moves' and 'Charge Moves'
pokemon_df['Fast Moves'] = pokemon_df['Fast Moves'].apply(safe_literal_eval)
pokemon_df['Charge Moves'] = pokemon_df['Charge Moves'].apply(safe_literal_eval)

In [5]:
# Load the Moveset dataset
moveset_df = pd.read_csv('extracted_data/Pokemon_GO_Details.csv')

In [6]:
# Initial check of the data
print(pokemon_df.head())

   Unnamed: 0    #                    Name          Type  Attack  Defense  \
0           0  1.0               Bulbasaur  Grass Poison   118.0    111.0
1       41616  2.0                 Ivysaur  Grass Poison   151.0    143.0
2       83232  3.0                Venusaur  Grass Poison   198.0    189.0
3      161262  3.0  Venusaur Mega Venusaur  Grass Poison   241.0    246.0
4      239292  4.0              Charmander          Fire   116.0     93.0

      HP             Fast Moves  \
0  128.0      [TackleVine Whip]
1  155.0  [Razor LeafVine Whip]
2  190.0  [Razor LeafVine Whip]
3  190.0                     []
4  118.0         [EmberScratch]

                                        Charge Moves
0       [FrustrationPower WhipReturnSeed BombSludge]
1      [FrustrationPower WhipReturnSludgeSolar Beam]
2  [BlizzardFrenzy PlantFrustrationReturnSludgeSo...
3                                                 []
4  [Flame BurstFlame ChargeFlamethrowerFrustratio...

In [7]:
print(moveset_df.head())

      ID     Pokemon Go   Type1   Type2    HP  Attack  Defense  Level  \
0  384.0  Mega Rayquaza  Dragon  Flying  22.0    36.0     21.0      1
1  384.0  Mega Rayquaza  Dragon  Flying  40.0    65.0     37.0      2
2  384.0  Mega Rayquaza  Dragon  Flying  52.0    84.0     48.0      3
3  384.0  Mega Rayquaza  Dragon  Flying  61.0   100.0     57.0      4
4  384.0  Mega Rayquaza  Dragon  Flying  70.0   113.0     65.0      5

   CP Multiplier   CP  ... FPower   FType FEnergy boost  FDuration  \
0       0.094000   80  ...   15.0  Dragon           9.0        1.1
1       0.166398  253  ...   15.0  Dragon           9.0        1.1
2       0.215732  425  ...   15.0  Dragon           9.0        1.1
3       0.255720  598  ...   15.0  Dragon           9.0        1.1
4       0.290250  770  ...   15.0  Dragon           9.0        1.1

    Charged Move CPower   CType CEnergy cost  CDuration  Damage window start
0  Dragon Ascent  140.0  Flying         50.0        3.5                  3.2
1  Dragon Ascent  140.0  Flying         50.0        3.5                  3.2
2  Dragon Ascent  140.0  Flying         50.0        3.5                  3.2
3  Dragon Ascent  140.0  Flying         50.0        3.5                  3.2
4  Dragon Ascent  140.0  Flying         50.0        3.5                  3.2

[5 rows x 21 columns]

In [8]:
moveset_df.shape

(737613, 21)

In [9]:
pokemon_df.shape

(1031, 9)

In [10]:
moveset_df.columns

Index(['ID', 'Pokemon Go', 'Type1', 'Type2', 'HP', 'Attack', 'Defense',
       'Level', 'CP Multiplier', 'CP', 'Fast Move', 'FPower', 'FType',
       'FEnergy boost', 'FDuration', 'Charged Move', 'CPower', 'CType',
       'CEnergy cost', 'CDuration', 'Damage window start'],
      dtype='object')

In [11]:
pokemon_df.columns

Index(['Unnamed: 0', '#', 'Name', 'Type', 'Attack', 'Defense', 'HP',
       'Fast Moves', 'Charge Moves'],
      dtype='object')

In [12]:
pokemon_df['Fast Moves']

0             [TackleVine Whip]
1         [Razor LeafVine Whip]
2         [Razor LeafVine Whip]
3                            []
4                [EmberScratch]
                 ...
1026    [Dragon BreathIce Fang]
1027    [Dragon BreathIce Fang]
1028    [Dragon BreathIce Fang]
1029                 [Astonish]
1030              [AstonishHex]
Name: Fast Moves, Length: 1031, dtype: object

In [13]:
moveset_df = pd.read_csv('extracted_data/pokemon_go_moveset.csv')

# Create a sorted list of unique moves by length (longest first)
unique_moves = sorted(moveset_df['Name'].unique(), key=len, reverse=True)

# Create a regex pattern to match any of the unique moves
# We use re.escape to handle moves with special characters (e.g., "Power-Up Punch")
moves_pattern = '|'.join(re.escape(move) for move in unique_moves)

def find_moves(moves_string):
    """
    Finds all moves in a concatenated moves string using regex pattern matching.
    :param moves_string: A string containing concatenated move names.
    :return: A list of separated move names.
    """
    if pd.isnull(moves_string):
        return []
    found_moves = re.findall(moves_pattern, moves_string)
    return found_moves

# Apply the find_moves function to separate the 'Fast Moves' and 'Charge Moves'
pokemon_df['Fast Moves'] = pokemon_df['Fast Moves'].astype(str).apply(find_moves)
pokemon_df['Charge Moves'] = pokemon_df['Charge Moves'].astype(str).apply(find_moves)

# Verify the results
print(pokemon_df[['Name', 'Fast Moves', 'Charge Moves']].head())

                     Name               Fast Moves  \
0               Bulbasaur      [Tackle, Vine Whip]
1                 Ivysaur  [Razor Leaf, Vine Whip]
2                Venusaur  [Razor Leaf, Vine Whip]
3  Venusaur Mega Venusaur                       []
4              Charmander         [Ember, Scratch]

                                        Charge Moves
0  [Frustration, Power Whip, Return, Seed Bomb, S...
1  [Frustration, Power Whip, Return, Sludge, Sola...
2  [Blizzard, Frenzy Plant, Frustration, Return, ...
3                                                 []
4  [Flame Burst, Flame Charge, Flamethrower, Frus...

In [14]:
pokemon_df.head(5)

,Unnamed: 0,#,Name,Type,Attack,Defense,HP,Fast Moves,Charge Moves
0,0,1.0,Bulbasaur,Grass Poison,118.0,111.0,128.0,"[Tackle, Vine Whip]","[Frustration, Power Whip, Return, Seed Bomb, S..."
1,41616,2.0,Ivysaur,Grass Poison,151.0,143.0,155.0,"[Razor Leaf, Vine Whip]","[Frustration, Power Whip, Return, Sludge, Sola..."
2,83232,3.0,Venusaur,Grass Poison,198.0,189.0,190.0,"[Razor Leaf, Vine Whip]","[Blizzard, Frenzy Plant, Frustration, Return, ..."
3,161262,3.0,Venusaur Mega Venusaur,Grass Poison,241.0,246.0,190.0,[],[]
4,239292,4.0,Charmander,Fire,116.0,93.0,118.0,"[Ember, Scratch]","[Flame Burst, Flame Charge, Flamethrower, Frus..."

In [15]:
# Load the detailed Pok√©mon dataset
details_df = pd.read_csv('extracted_data/Pokemon_GO_Details.csv')

# Function to filter Pok√©mon based on league CP limits
def filter_for_league(details_df, max_cp):
    """
    Filter the Pok√©mon based on CP limits for a specific league.
    
    :param details_df: DataFrame with Pok√©mon details including CP.
    :param max_cp: Maximum CP limit for the league. Use None for no limit (Master League).
    :return: Filtered DataFrame.
    """
    if max_cp:
        return details_df[details_df['CP'] <= max_cp]
    else:
        return details_df

# Filter out Pok√©mon with 'Mega' or 'Primal' in their names
filtered_df = details_df[~details_df['Pokemon Go'].str.contains('Mega|Primal', regex=True)]

# Filter Pok√©mon for each league
great_league_df = filter_for_league(filtered_df, 1500)
ultra_league_df = filter_for_league(filtered_df, 2500)
master_league_df = filter_for_league(filtered_df, None)  # No CP limit for Master League

In [16]:
filtered_df.head()

,ID,Pokemon Go,Type1,Type2,HP,Attack,Defense,Level,CP Multiplier,CP,...,FPower,FType,FEnergy boost,FDuration,Charged Move,CPower,CType,CEnergy cost,CDuration,Damage window start
102,150.0,Shadow Mewtwo,Psychic,NaN,21.0,35.0,15.0,1,0.094000,59,...,20.0,Psychic,15.0,1.6,Psystrike,90.0,Psychic,50.0,2.3,1.0
103,150.0,Shadow Mewtwo,Psychic,NaN,38.0,62.0,27.0,2,0.166398,185,...,20.0,Psychic,15.0,1.6,Psystrike,90.0,Psychic,50.0,2.3,1.0
104,150.0,Shadow Mewtwo,Psychic,NaN,49.0,80.0,35.0,3,0.215732,311,...,20.0,Psychic,15.0,1.6,Psystrike,90.0,Psychic,50.0,2.3,1.0
105,150.0,Shadow Mewtwo,Psychic,NaN,58.0,95.0,42.0,4,0.255720,437,...,20.0,Psychic,15.0,1.6,Psystrike,90.0,Psychic,50.0,2.3,1.0
106,150.0,Shadow Mewtwo,Psychic,NaN,66.0,108.0,48.0,5,0.290250,563,...,20.0,Psychic,15.0,1.6,Psystrike,90.0,Psychic,50.0,2.3,1.0

In [17]:
pokemon_df[pokemon_df['Name'] == 'Palkia Origin Forme']

,Unnamed: 0,#,Name,Type,Attack,Defense,HP,Fast Moves,Charge Moves
586,39186666,484.0,Palkia Origin Forme,Water Dragon,286.0,223.0,189.0,"[Dragon Breath, Dragon Tail]","[Aqua Tail, Draco Meteor, Fire Blast, Hydro Pump]"

In [18]:
filtered_df.shape

(708492, 21)

In [19]:
pokemon_df.shape

(1031, 9)

In [20]:
# Get unique Pok√©mon names from both datasets
unique_pokemon = set(pokemon_df['Name'])
unique_pokemon_filtered = set(filtered_df['Pokemon Go'])

In [21]:
# Identify Pok√©mon in pokemon_df not in filtered_df
missing_pokemon = unique_pokemon - unique_pokemon_filtered

In [22]:
pokemon_df[pokemon_df['Name'] == 'Palkia Origin Forme']

,Unnamed: 0,#,Name,Type,Attack,Defense,HP,Fast Moves,Charge Moves
586,39186666,484.0,Palkia Origin Forme,Water Dragon,286.0,223.0,189.0,"[Dragon Breath, Dragon Tail]","[Aqua Tail, Draco Meteor, Fire Blast, Hydro Pump]"

In [23]:
# Complete CPM values for levels 1 through 51
cpm_values = {
    1: 0.094, 2: 0.16639787, 3: 0.21573247, 4: 0.25572005,
    5: 0.29024988, 6: 0.3210876, 7: 0.34921268, 8: 0.37523559,
    9: 0.39956728, 10: 0.42250001, 11: 0.44310755, 12: 0.46279839,
    13: 0.48168495, 14: 0.49985844, 15: 0.51739395, 16: 0.53435433,
    17: 0.55079269, 18: 0.56675452, 19: 0.58227891, 20: 0.59740001,
    21: 0.61215729, 22: 0.62656713, 23: 0.64065295, 24: 0.65443563,
    25: 0.667934, 26: 0.68116492, 27: 0.69414365, 28: 0.70688421,
    29: 0.71939909, 30: 0.7317, 31: 0.73776948, 32: 0.74378943,
    33: 0.74976104, 34: 0.75568551, 35: 0.76156384, 36: 0.76739717,
    37: 0.7731865, 38: 0.77893275, 39: 0.78463697, 40: 0.79030001,
    41: 0.79530001, 42: 0.8003, 43: 0.8053, 44: 0.81029999,
    45: 0.81529999, 46: 0.8203, 47: 0.8253, 48: 0.83029999,
    49: 0.8353, 50: 0.84029999, 51: 0.84384999  # Buddy Boost Level
}

In [24]:
import numpy as np

# Define the function to calculate CP
def calculate_cp(attack, defense, stamina, cpm):
    # Check if any of the parameters are NaN and return NaN for CP as well
    if pd.isnull(attack) or pd.isnull(defense) or pd.isnull(stamina) or pd.isnull(cpm):
        return np.nan  # Return a NaN for CP if any stat is missing
    
    # Proceed with the calculation if all values are present
    return max(10, int(((attack + 15) * np.sqrt(defense + 15) * np.sqrt(stamina + 15) * (cpm ** 2)) / 10))

# Initialize a list to store Pok√©mon stats at each level
all_levels_stats = []

# Iterate over each Pok√©mon and each level to calculate stats
for _, pokemon in pokemon_df.iterrows():
    for level, cpm in cpm_values.items():
        cp = calculate_cp(pokemon['Attack'], pokemon['Defense'], pokemon['HP'], cpm)
        all_levels_stats.append({
            'Name': pokemon['Name'], 
            'Type': pokemon['Type'],  # Assuming 'Type' column exists, adjust as needed
            'Level': level, 
            'CP': cp,
            'Attack': pokemon['Attack'], 
            'Defense': pokemon['Defense'], 
            'HP': pokemon['HP']
        })

# Convert the stats list to a DataFrame
pokemon_levels_df = pd.DataFrame(all_levels_stats)

In [25]:
# Check for entries with NaN CP values to identify potential issues
nan_cp_entries = pokemon_levels_df[pokemon_levels_df['CP'].isna()]

In [26]:
pokemon_levels_df[pokemon_levels_df['Name'] == 'Palkia Origin Forme']

,Name,Type,Level,CP,Attack,Defense,HP
29886,Palkia Origin Forme,Water Dragon,1,58.0,286.0,223.0,189.0
29887,Palkia Origin Forme,Water Dragon,2,183.0,286.0,223.0,189.0
29888,Palkia Origin Forme,Water Dragon,3,308.0,286.0,223.0,189.0
29889,Palkia Origin Forme,Water Dragon,4,433.0,286.0,223.0,189.0
29890,Palkia Origin Forme,Water Dragon,5,558.0,286.0,223.0,189.0
29891,Palkia Origin Forme,Water Dragon,6,683.0,286.0,223.0,189.0
29892,Palkia Origin Forme,Water Dragon,7,808.0,286.0,223.0,189.0
29893,Palkia Origin Forme,Water Dragon,8,933.0,286.0,223.0,189.0
29894,Palkia Origin Forme,Water Dragon,9,1058.0,286.0,223.0,189.0
29895,Palkia Origin Forme,Water Dragon,10,1183.0,286.0,223.0,189.0
29896,Palkia Origin Forme,Water Dragon,11,1302.0,286.0,223.0,189.0
29897,Palkia Origin Forme,Water Dragon,12,1420.0,286.0,223.0,189.0
29898,Palkia Origin Forme,Water Dragon,13,1538.0,286.0,223.0,189.0
29899,Palkia Origin Forme,Water Dragon,14,1657.0,286.0,223.0,189.0
29900,Palkia Origin Forme,Water Dragon,15,1775.0,286.0,223.0,189.0
29901,Palkia Origin Forme,Water Dragon,16,1893.0,286.0,223.0,189.0
29902,Palkia Origin Forme,Water Dragon,17,2012.0,286.0,223.0,189.0
29903,Palkia Origin Forme,Water Dragon,18,2130.0,286.0,223.0,189.0
29904,Palkia Origin Forme,Water Dragon,19,2248.0,286.0,223.0,189.0
29905,Palkia Origin Forme,Water Dragon,20,2367.0,286.0,223.0,189.0
29906,Palkia Origin Forme,Water Dragon,21,2485.0,286.0,223.0,189.0
29907,Palkia Origin Forme,Water Dragon,22,2603.0,286.0,223.0,189.0
29908,Palkia Origin Forme,Water Dragon,23,2722.0,286.0,223.0,189.0
29909,Palkia Origin Forme,Water Dragon,24,2840.0,286.0,223.0,189.0
29910,Palkia Origin Forme,Water Dragon,25,2958.0,286.0,223.0,189.0
29911,Palkia Origin Forme,Water Dragon,26,3077.0,286.0,223.0,189.0
29912,Palkia Origin Forme,Water Dragon,27,3195.0,286.0,223.0,189.0
29913,Palkia Origin Forme,Water Dragon,28,3314.0,286.0,223.0,189.0
29914,Palkia Origin Forme,Water Dragon,29,3432.0,286.0,223.0,189.0
29915,Palkia Origin Forme,Water Dragon,30,3550.0,286.0,223.0,189.0
29916,Palkia Origin Forme,Water Dragon,31,3610.0,286.0,223.0,189.0
29917,Palkia Origin Forme,Water Dragon,32,3669.0,286.0,223.0,189.0
29918,Palkia Origin Forme,Water Dragon,33,3728.0,286.0,223.0,189.0
29919,Palkia Origin Forme,Water Dragon,34,3787.0,286.0,223.0,189.0
29920,Palkia Origin Forme,Water Dragon,35,3846.0,286.0,223.0,189.0
29921,Palkia Origin Forme,Water Dragon,36,3905.0,286.0,223.0,189.0
29922,Palkia Origin Forme,Water Dragon,37,3964.0,286.0,223.0,189.0
29923,Palkia Origin Forme,Water Dragon,38,4024.0,286.0,223.0,189.0
29924,Palkia Origin Forme,Water Dragon,39,4083.0,286.0,223.0,189.0
29925,Palkia Origin Forme,Water Dragon,40,4142.0,286.0,223.0,189.0
29926,Palkia Origin Forme,Water Dragon,41,4195.0,286.0,223.0,189.0
29927,Palkia Origin Forme,Water Dragon,42,4247.0,286.0,223.0,189.0
29928,Palkia Origin Forme,Water Dragon,43,4301.0,286.0,223.0,189.0
29929,Palkia Origin Forme,Water Dragon,44,4354.0,286.0,223.0,189.0
29930,Palkia Origin Forme,Water Dragon,45,4408.0,286.0,223.0,189.0
29931,Palkia Origin Forme,Water Dragon,46,4462.0,286.0,223.0,189.0
29932,Palkia Origin Forme,Water Dragon,47,4517.0,286.0,223.0,189.0
29933,Palkia Origin Forme,Water Dragon,48,4572.0,286.0,223.0,189.0
29934,Palkia Origin Forme,Water Dragon,49,4627.0,286.0,223.0,189.0
29935,Palkia Origin Forme,Water Dragon,50,4683.0,286.0,223.0,189.0
29936,Palkia Origin Forme,Water Dragon,51,4722.0,286.0,223.0,189.0

In [27]:
# Drop rows where 'Name' is NaN
pokemon_levels_df_cleaned = pokemon_levels_df.dropna(subset=['Name'])

In [28]:
# Review the cleaned DataFrame
print(pokemon_levels_df_cleaned.head())

        Name          Type  Level     CP  Attack  Defense     HP
0  Bulbasaur  Grass Poison      1   15.0   118.0    111.0  128.0
1  Bulbasaur  Grass Poison      2   49.0   118.0    111.0  128.0
2  Bulbasaur  Grass Poison      3   83.0   118.0    111.0  128.0
3  Bulbasaur  Grass Poison      4  116.0   118.0    111.0  128.0
4  Bulbasaur  Grass Poison      5  150.0   118.0    111.0  128.0

In [29]:
# Optionally, check the shape or info to confirm rows have been dropped
print(pokemon_levels_df_cleaned.shape)

(52530, 7)

In [30]:
filtered_df

,ID,Pokemon Go,Type1,Type2,HP,Attack,Defense,Level,CP Multiplier,CP,...,FPower,FType,FEnergy boost,FDuration,Charged Move,CPower,CType,CEnergy cost,CDuration,Damage window start
102,150.0,Shadow Mewtwo,Psychic,NaN,21.0,35.0,15.0,1,0.094000,59,...,20.0,Psychic,15.0,1.60,Psystrike,90.0,Psychic,50.0,2.3,1.0
103,150.0,Shadow Mewtwo,Psychic,NaN,38.0,62.0,27.0,2,0.166398,185,...,20.0,Psychic,15.0,1.60,Psystrike,90.0,Psychic,50.0,2.3,1.0
104,150.0,Shadow Mewtwo,Psychic,NaN,49.0,80.0,35.0,3,0.215732,311,...,20.0,Psychic,15.0,1.60,Psystrike,90.0,Psychic,50.0,2.3,1.0
105,150.0,Shadow Mewtwo,Psychic,NaN,58.0,95.0,42.0,4,0.255720,437,...,20.0,Psychic,15.0,1.60,Psystrike,90.0,Psychic,50.0,2.3,1.0
106,150.0,Shadow Mewtwo,Psychic,NaN,66.0,108.0,48.0,5,0.290250,563,...,20.0,Psychic,15.0,1.60,Psystrike,90.0,Psychic,50.0,2.3,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737608,129.0,Shadow Magikarp,Water,NaN,82.0,41.0,70.0,47,0.825300,299,...,0.0,Water,20.0,1.73,Frustration,10.0,Normal,33.0,2.0,1.0
737609,129.0,Shadow Magikarp,Water,NaN,83.0,41.0,71.0,48,0.830300,303,...,0.0,Water,20.0,1.73,Frustration,10.0,Normal,33.0,2.0,1.0
737610,129.0,Shadow Magikarp,Water,NaN,83.0,41.0,71.0,49,0.835300,306,...,0.0,Water,20.0,1.73,Frustration,10.0,Normal,33.0,2.0,1.0
737611,129.0,Shadow Magikarp,Water,NaN,84.0,41.0,72.0,50,0.840300,310,...,0.0,Water,20.0,1.73,Frustration,10.0,Normal,33.0,2.0,1.0
737612,129.0,Shadow Magikarp,Water,NaN,84.0,42.0,72.0,51,0.845300,314,...,0.0,Water,20.0,1.73,Frustration,10.0,Normal,33.0,2.0,1.0

In [31]:
# Rename the 'Pokemon Go' column to 'Name' in filtered_df
filtered_df.rename(columns={'Pokemon Go': 'Name'}, inplace=True)

/var/folders/j9/7txjkxjn6zs87g_3bm9f81fr0000gn/T/ipykernel_55565/1546274711.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.rename(columns={'Pokemon Go': 'Name'}, inplace=True)

In [32]:
missing_names = set(pokemon_levels_df_cleaned['Name']) - set(filtered_df['Name'])

In [33]:
missing_pokemon_df = pd.DataFrame(list(missing_names), columns=['Name'])

In [34]:
filtered_df_updated = pd.concat([filtered_df, missing_pokemon_df], ignore_index=True)

In [35]:
combined_df = pd.merge(filtered_df_updated, pokemon_levels_df_cleaned, on=['Name'], how='left')

In [36]:
pokemon_types = [
    "Normal", "Fire", "Water", "Electric", "Grass", "Ice",
    "Fighting", "Poison", "Ground", "Flying", "Psychic", "Bug",
    "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy"
]

In [37]:
combined_df.isna().sum()

ID                        14127
Name                          0
Type1                     14127
Type2                  11548491
HP_x                      14127
Attack_x                  14127
Defense_x                 14127
Level_x                   14127
CP Multiplier             14127
CP_x                      14127
Fast Move                 14127
FPower                    14127
FType                     14127
FEnergy boost             14127
FDuration                 14127
Charged Move              14127
CPower                    14127
CType                     14127
CEnergy cost              14127
CDuration                 14127
Damage window start       91596
Type                     280296
Level_y                  280296
CP_y                     280296
Attack_y                 280296
Defense_y                280296
HP_y                     280296
dtype: int64

In [38]:
import dask.dataframe as dd

# Convert the Pandas DataFrame to a Dask DataFrame
dask_df = dd.from_pandas(combined_df, npartitions=10)  # Adjust npartitions based on your dataset and memory capacity

In [39]:
combined_df.to_parquet('pokemon_go.parquet', engine='pyarrow')

In [40]:
# Now read the data directly into PySpark
from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("App Name") \
    .config("spark.driver.memory", "4g") \
    .config("spark.executor.memory", "4g") \
    .getOrCreate()

spark_df = spark.read.parquet('pokemon_go.parquet')

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/04/13 17:21:16 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
24/04/13 17:21:29 WARN GarbageCollectionMetrics: To enable non-built-in garbage collector(s) List(G1 Concurrent GC), users should configure it(them) to spark.eventLog.gcMetrics.youngGenerationGarbageCollectors or spark.eventLog.gcMetrics.oldGenerationGarbageCollectors

In [41]:
from pyspark.sql.functions import split

# Splitting the "Type" column when there's a clear separator
split_col = split(spark_df['Type'], ' ')  # Use the appropriate separator here
spark_df = spark_df.withColumn('Type1', split_col.getItem(0))
spark_df = spark_df.withColumn('Type2', split_col.getItem(1))

In [42]:
from pyspark.sql.functions import udf
from pyspark.sql.types import ArrayType, StringType

# Example UDF to split concatenated types
def split_pokemon_type(type_string):
    known_types = ["Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison", "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy"]
    for pokemon_type in known_types:
        if pokemon_type in type_string:
            # Assume the remaining string is Type2
            remaining_type = type_string.replace(pokemon_type, '', 1).strip()
            return [pokemon_type, remaining_type if remaining_type else None]
    return [None, None]

# Register UDF
split_type_udf = udf(split_pokemon_type, ArrayType(StringType()))

# Apply UDF to split "Type" into "Type1" and "Type2"
spark_df = spark_df.withColumn("Types", split_type_udf("Type")) \
                   .withColumn("Type1", split_col.getItem(0)) \
                   .withColumn("Type2", split_col.getItem(1)) \
                   .drop("Types")

In [43]:
from pyspark.sql.functions import desc

# Assuming 'id' is a column you can sort by to determine the "bottom" rows
# If you have a timestamp or other sequential column, you can use that instead
spark_df.orderBy(desc("id")).show(20)

24/04/13 17:22:08 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+------+---------+-----+-----+----+--------+---------+-------+-------------+----+---------+------+-----+-------------+---------+------------+------+-----+------------+---------+-------------------+-----------+-------+------+--------+---------+-----+
|    ID|     Name|Type1|Type2|HP_x|Attack_x|Defense_x|Level_x|CP Multiplier|CP_x|Fast Move|FPower|FType|FEnergy boost|FDuration|Charged Move|CPower|CType|CEnergy cost|CDuration|Damage window start|       Type|Level_y|  CP_y|Attack_y|Defense_y| HP_y|
+------+---------+-----+-----+----+--------+---------+-------+-------------+----+---------+------+-----+-------------+---------+------------+------+-----+------------+---------+-------------------+-----------+-------+------+--------+---------+-----+
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|    1.0|  49.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|   21.0|2110.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|    2.0| 155.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|    3.0| 262.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|    4.0| 368.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|    5.0| 474.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|    6.0| 580.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|    7.0| 686.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|    8.0| 792.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|    9.0| 899.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|   10.0|1005.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|   11.0|1105.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|   12.0|1206.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|   13.0|1306.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|   14.0|1407.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|   15.0|1507.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|   16.0|1607.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|   17.0|1708.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|   18.0|1808.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|20.0|    25.0|     19.0|    1.0|        0.094|49.0|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|Steel Ghost|   19.0|1909.0|   252.0|    190.0|202.0|
+------+---------+-----+-----+----+--------+---------+-------+-------------+----+---------+------+-----+-------------+---------+------------+------+-----+------------+---------+-------------------+-----------+-------+------+--------+---------+-----+
only showing top 20 rows

In [44]:
num_rows = spark_df.count()
print(f"The DataFrame contains {num_rows} rows.")

The DataFrame contains 22132419 rows.

In [45]:
from pyspark.sql.functions import col

# Filter for rows where the level is outside the 1 to 51 range
invalid_levels_df = spark_df.filter((col("Level_y") < 1) | (col("Level_y") > 51))

# Count the number of rows that fall outside the desired level range
num_invalid_levels = invalid_levels_df.count()

if num_invalid_levels == 0:
    print("All levels are within the range 1 to 51.")
else:
    print(f"There are {num_invalid_levels} rows with levels outside the range 1 to 51.")

All levels are within the range 1 to 51.

In [46]:
from pyspark.sql.functions import countDistinct

# Count the distinct levels in the DataFrame
distinct_levels = spark_df.agg(countDistinct(col("Level_y")).alias("distinct_levels")).collect()[0]["distinct_levels"]

# Assuming levels should be integers from 1 to 51, there should be 51 distinct levels
if distinct_levels == 51:
    print("All levels from 1 to 51 are represented in the DataFrame.")
else:
    print(f"Not all levels from 1 to 51 are represented. There are {distinct_levels} distinct levels.")

All levels from 1 to 51 are represented in the DataFrame.

In [47]:
from pyspark.sql.functions import col

# Group by the "Level" column and count occurrences
level_counts_df = spark_df.groupBy("Level_y").count().orderBy("Level_y")

# Collect the aggregated data to the driver node as a list of rows
level_counts = level_counts_df.collect()

# Print the count of each level
for row in level_counts:
    print(f"Level {row['Level_y']}: {row['count']} occurrences")

Level None: 280296 occurrences
Level 1.0: 428473 occurrences
Level 2.0: 428473 occurrences
Level 3.0: 428473 occurrences
Level 4.0: 428473 occurrences
Level 5.0: 428473 occurrences
Level 6.0: 428473 occurrences
Level 7.0: 428473 occurrences
Level 8.0: 428473 occurrences
Level 9.0: 428473 occurrences
Level 10.0: 428473 occurrences
Level 11.0: 428473 occurrences
Level 12.0: 428473 occurrences
Level 13.0: 428473 occurrences
Level 14.0: 428473 occurrences
Level 15.0: 428473 occurrences
Level 16.0: 428473 occurrences
Level 17.0: 428473 occurrences
Level 18.0: 428473 occurrences
Level 19.0: 428473 occurrences
Level 20.0: 428473 occurrences
Level 21.0: 428473 occurrences
Level 22.0: 428473 occurrences
Level 23.0: 428473 occurrences
Level 24.0: 428473 occurrences
Level 25.0: 428473 occurrences
Level 26.0: 428473 occurrences
Level 27.0: 428473 occurrences
Level 28.0: 428473 occurrences
Level 29.0: 428473 occurrences
Level 30.0: 428473 occurrences
Level 31.0: 428473 occurrences
Level 32.0: 428473 occurrences
Level 33.0: 428473 occurrences
Level 34.0: 428473 occurrences
Level 35.0: 428473 occurrences
Level 36.0: 428473 occurrences
Level 37.0: 428473 occurrences
Level 38.0: 428473 occurrences
Level 39.0: 428473 occurrences
Level 40.0: 428473 occurrences
Level 41.0: 428473 occurrences
Level 42.0: 428473 occurrences
Level 43.0: 428473 occurrences
Level 44.0: 428473 occurrences
Level 45.0: 428473 occurrences
Level 46.0: 428473 occurrences
Level 47.0: 428473 occurrences
Level 48.0: 428473 occurrences
Level 49.0: 428473 occurrences
Level 50.0: 428473 occurrences
Level 51.0: 428473 occurrences

In [48]:
from pyspark.sql.functions import col

# Filter the Spark DataFrame for Rayquaza
rayquaza_df = spark_df.filter(col("Name") == "Rayquaza")

In [49]:
# Convert the filtered Spark DataFrame to a Pandas DataFrame
rayquaza_pd_df = rayquaza_df.toPandas()

# Display the first few rows to check the DataFrame
rayquaza_pd_df.head()

,ID,Name,Type1,Type2,HP_x,Attack_x,Defense_x,Level_x,CP Multiplier,CP_x,...,CType,CEnergy cost,CDuration,Damage window start,Type,Level_y,CP_y,Attack_y,Defense_y,HP_y
0,384.0,Rayquaza,Dragon,Flying,21.0,28.0,17.0,1.0,0.094,54.0,...,Flying,50.0,3.5,3.2,Dragon Flying,1.0,54.0,284.0,170.0,213.0
1,384.0,Rayquaza,Dragon,Flying,21.0,28.0,17.0,1.0,0.094,54.0,...,Flying,50.0,3.5,3.2,Dragon Flying,2.0,170.0,284.0,170.0,213.0
2,384.0,Rayquaza,Dragon,Flying,21.0,28.0,17.0,1.0,0.094,54.0,...,Flying,50.0,3.5,3.2,Dragon Flying,3.0,285.0,284.0,170.0,213.0
3,384.0,Rayquaza,Dragon,Flying,21.0,28.0,17.0,1.0,0.094,54.0,...,Flying,50.0,3.5,3.2,Dragon Flying,4.0,401.0,284.0,170.0,213.0
4,384.0,Rayquaza,Dragon,Flying,21.0,28.0,17.0,1.0,0.094,54.0,...,Flying,50.0,3.5,3.2,Dragon Flying,5.0,517.0,284.0,170.0,213.0

In [50]:
# Assuming 'spark_df' is your Spark DataFrame
palkia_origin_df = spark_df.filter(col("Name") == "Palkia Origin Forme")

In [51]:
# Convert the filtered Spark DataFrame to a Pandas DataFrame
palkia_origin_pd_df = palkia_origin_df.toPandas()

# Display the DataFrame to inspect "Palkia Origin Forme" data
palkia_origin_pd_df

,ID,Name,Type1,Type2,HP_x,Attack_x,Defense_x,Level_x,CP Multiplier,CP_x,...,CType,CEnergy cost,CDuration,Damage window start,Type,Level_y,CP_y,Attack_y,Defense_y,HP_y
0,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,1.0,58.0,286.0,223.0,189.0
1,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,2.0,183.0,286.0,223.0,189.0
2,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,3.0,308.0,286.0,223.0,189.0
3,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,4.0,433.0,286.0,223.0,189.0
4,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,5.0,558.0,286.0,223.0,189.0
5,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,6.0,683.0,286.0,223.0,189.0
6,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,7.0,808.0,286.0,223.0,189.0
7,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,8.0,933.0,286.0,223.0,189.0
8,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,9.0,1058.0,286.0,223.0,189.0
9,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,10.0,1183.0,286.0,223.0,189.0
10,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,11.0,1302.0,286.0,223.0,189.0
11,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,12.0,1420.0,286.0,223.0,189.0
12,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,13.0,1538.0,286.0,223.0,189.0
13,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,14.0,1657.0,286.0,223.0,189.0
14,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,15.0,1775.0,286.0,223.0,189.0
15,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,16.0,1893.0,286.0,223.0,189.0
16,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,17.0,2012.0,286.0,223.0,189.0
17,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,18.0,2130.0,286.0,223.0,189.0
18,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,19.0,2248.0,286.0,223.0,189.0
19,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,20.0,2367.0,286.0,223.0,189.0
20,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,21.0,2485.0,286.0,223.0,189.0
21,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,22.0,2603.0,286.0,223.0,189.0
22,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,23.0,2722.0,286.0,223.0,189.0
23,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,24.0,2840.0,286.0,223.0,189.0
24,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,25.0,2958.0,286.0,223.0,189.0
25,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,26.0,3077.0,286.0,223.0,189.0
26,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,27.0,3195.0,286.0,223.0,189.0
27,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,28.0,3314.0,286.0,223.0,189.0
28,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,29.0,3432.0,286.0,223.0,189.0
29,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,30.0,3550.0,286.0,223.0,189.0
30,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,31.0,3610.0,286.0,223.0,189.0
31,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,32.0,3669.0,286.0,223.0,189.0
32,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,33.0,3728.0,286.0,223.0,189.0
33,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,34.0,3787.0,286.0,223.0,189.0
34,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,35.0,3846.0,286.0,223.0,189.0
35,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,36.0,3905.0,286.0,223.0,189.0
36,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,37.0,3964.0,286.0,223.0,189.0
37,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,38.0,4024.0,286.0,223.0,189.0
38,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,39.0,4083.0,286.0,223.0,189.0
39,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,40.0,4142.0,286.0,223.0,189.0
40,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,41.0,4195.0,286.0,223.0,189.0
41,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,42.0,4247.0,286.0,223.0,189.0
42,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,43.0,4301.0,286.0,223.0,189.0
43,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,44.0,4354.0,286.0,223.0,189.0
44,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,45.0,4408.0,286.0,223.0,189.0
45,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,46.0,4462.0,286.0,223.0,189.0
46,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,47.0,4517.0,286.0,223.0,189.0
47,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,48.0,4572.0,286.0,223.0,189.0
48,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,49.0,4627.0,286.0,223.0,189.0
49,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,50.0,4683.0,286.0,223.0,189.0
50,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,51.0,4722.0,286.0,223.0,189.0

In [52]:
palkia_origin_pd_df.head(1)

,ID,Name,Type1,Type2,HP_x,Attack_x,Defense_x,Level_x,CP Multiplier,CP_x,...,CType,CEnergy cost,CDuration,Damage window start,Type,Level_y,CP_y,Attack_y,Defense_y,HP_y
0,NaN,Palkia Origin Forme,Water,Dragon,NaN,NaN,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,Water Dragon,1.0,58.0,286.0,223.0,189.0

In [53]:
rayquaza_pd_df.head(1)

,ID,Name,Type1,Type2,HP_x,Attack_x,Defense_x,Level_x,CP Multiplier,CP_x,...,CType,CEnergy cost,CDuration,Damage window start,Type,Level_y,CP_y,Attack_y,Defense_y,HP_y
0,384.0,Rayquaza,Dragon,Flying,21.0,28.0,17.0,1.0,0.094,54.0,...,Flying,50.0,3.5,3.2,Dragon Flying,1.0,54.0,284.0,170.0,213.0

In [54]:
palkia_origin_pd_df.columns

Index(['ID', 'Name', 'Type1', 'Type2', 'HP_x', 'Attack_x', 'Defense_x',
       'Level_x', 'CP Multiplier', 'CP_x', 'Fast Move', 'FPower', 'FType',
       'FEnergy boost', 'FDuration', 'Charged Move', 'CPower', 'CType',
       'CEnergy cost', 'CDuration', 'Damage window start', 'Type', 'Level_y',
       'CP_y', 'Attack_y', 'Defense_y', 'HP_y'],
      dtype='object')

In [55]:
# Adjust display settings to show all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

In [56]:
# List of columns to be dropped
columns_to_drop = ["HP_x", "Attack_x", "Defense_x", "Level_x", "CP_x", "Type"]

# Dropping the specified columns from the DataFrame
cleaned_df = spark_df.drop(*columns_to_drop)

In [57]:
cleaned_df.orderBy(desc("id")).show(20)

+------+---------+-----+-----+-------------+---------+------+-----+-------------+---------+------------+------+-----+------------+---------+-------------------+-------+------+--------+---------+-----+
|    ID|     Name|Type1|Type2|CP Multiplier|Fast Move|FPower|FType|FEnergy boost|FDuration|Charged Move|CPower|CType|CEnergy cost|CDuration|Damage window start|Level_y|  CP_y|Attack_y|Defense_y| HP_y|
+------+---------+-----+-----+-------------+---------+------+-----+-------------+---------+------------+------+-----+------------+---------+-------------------+-------+------+--------+---------+-----+
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|    1.0|  49.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|   21.0|2110.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|    2.0| 155.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|    3.0| 262.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|    4.0| 368.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|    5.0| 474.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|    6.0| 580.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|    7.0| 686.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|    8.0| 792.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|    9.0| 899.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|   10.0|1005.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|   11.0|1105.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|   12.0|1206.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|   13.0|1306.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|   14.0|1407.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|   15.0|1507.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|   16.0|1607.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|   17.0|1708.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|   18.0|1808.0|   252.0|    190.0|202.0|
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|   19.0|1909.0|   252.0|    190.0|202.0|
+------+---------+-----+-----+-------------+---------+------+-----+-------------+---------+------------+------+-----+------------+---------+-------------------+-------+------+--------+---------+-----+
only showing top 20 rows

In [58]:
# Iterate over each column in the DataFrame
for column_name in cleaned_df.columns:
    # Check if the column name ends with '_y'
    if column_name.endswith('_y'):
        # Define a new column name without the '_y' suffix
        new_column_name = column_name[:-2]
        # Rename the column
        cleaned_df = cleaned_df.withColumnRenamed(column_name, new_column_name)

In [59]:
cleaned_df.orderBy(desc("id")).show(1)

+------+---------+-----+-----+-------------+---------+------+-----+-------------+---------+------------+------+-----+------------+---------+-------------------+-----+----+------+-------+-----+
|    ID|     Name|Type1|Type2|CP Multiplier|Fast Move|FPower|FType|FEnergy boost|FDuration|Charged Move|CPower|CType|CEnergy cost|CDuration|Damage window start|Level|  CP|Attack|Defense|   HP|
+------+---------+-----+-----+-------------+---------+------+-----+-------------+---------+------------+------+-----+------------+---------+-------------------+-----+----+------+-------+-----+
|1000.0|Gholdengo|Steel|Ghost|        0.094|      Hex|  10.0|Ghost|         16.0|      1.2| Shadow Ball| 100.0|Ghost|        50.0|      3.0|                2.4|  1.0|49.0| 252.0|  190.0|202.0|
+------+---------+-----+-----+-------------+---------+------+-----+-------------+---------+------------+------+-----+------------+---------+-------------------+-----+----+------+-------+-----+
only showing top 1 row

In [60]:
from pyspark.sql.functions import col

# Filter for rows where Type1 is null
null_type1_df = cleaned_df.filter(col("Type1").isNull())

# Show the rows with null Type1
null_type1_df.count()

280296

In [61]:
from pyspark.sql.functions import col, when

# Filter out rows that are not Shadow Pok√©mon
non_shadow_df = cleaned_df.filter(~col("Name").startswith("Shadow"))

# Select distinct Name, Type1, and Type2 for non-Shadow Pok√©mon
type_mapping_df = non_shadow_df.select("Name", "Type1", "Type2").distinct()

In [62]:
# Collect the type mapping as a dictionary
type_mapping = {row["Name"]: (row["Type1"], row["Type2"]) for row in type_mapping_df.collect()}

# Define a UDF to impute Type1 and Type2 for Shadow Pok√©mon
from pyspark.sql.functions import udf
from pyspark.sql.types import StringType

def impute_type(name, type_val, type_num):
    # Check if the Pok√©mon is a Shadow version and has a NaN type
    if name.startswith("Shadow") and (type_val == "NaN" or type_val is None):
        # Extract the original Pok√©mon name
        original_name = name.replace("Shadow ", "")
        # Get the type from the mapping
        type1, type2 = type_mapping.get(original_name, (None, None))
        # Return the corresponding type
        return type1 if type_num == 1 else type2
    else:
        # If not a Shadow Pok√©mon or no NaN type, return the original type value
        return type_val

# Register the UDFs for Type1 and Type2
impute_type1_udf = udf(lambda name, type1: impute_type(name, type1, 1), StringType())
impute_type2_udf = udf(lambda name, type2: impute_type(name, type2, 2), StringType())

# Apply the UDFs to update Type1 and Type2 in the DataFrame
cleaned_df = cleaned_df.withColumn("Type1", impute_type1_udf(col("Name"), col("Type1")))
cleaned_df = cleaned_df.withColumn("Type2", impute_type2_udf(col("Name"), col("Type2")))

In [63]:
cleaned_df.filter(col("Name").startswith("Shadow")).show(1)

+-----+-------------+-------+-----+-------------+---------+------+-------+-------------+---------+------------+------+-------+------------+---------+-------------------+-----+----+------+-------+----+
|   ID|         Name|  Type1|Type2|CP Multiplier|Fast Move|FPower|  FType|FEnergy boost|FDuration|Charged Move|CPower|  CType|CEnergy cost|CDuration|Damage window start|Level|  CP|Attack|Defense|  HP|
+-----+-------------+-------+-----+-------------+---------+------+-------+-------------+---------+------------+------+-------+------------+---------+-------------------+-----+----+------+-------+----+
|150.0|Shadow Mewtwo|Psychic| NULL|        0.094|Confusion|  20.0|Psychic|         15.0|      1.6|   Psystrike|  90.0|Psychic|        50.0|      2.3|                1.0| NULL|NULL|  NULL|   NULL|NULL|
+-----+-------------+-------+-----+-------------+---------+------+-------+-------------+---------+------------+------+-------+------------+---------+-------------------+-----+----+------+-------+----+
only showing top 1 row

In [64]:
# Complete CPM values for levels 1 through 51
cpm_values = {
    1: 0.094, 2: 0.16639787, 3: 0.21573247, 4: 0.25572005,
    5: 0.29024988, 6: 0.3210876, 7: 0.34921268, 8: 0.37523559,
    9: 0.39956728, 10: 0.42250001, 11: 0.44310755, 12: 0.46279839,
    13: 0.48168495, 14: 0.49985844, 15: 0.51739395, 16: 0.53435433,
    17: 0.55079269, 18: 0.56675452, 19: 0.58227891, 20: 0.59740001,
    21: 0.61215729, 22: 0.62656713, 23: 0.64065295, 24: 0.65443563,
    25: 0.667934, 26: 0.68116492, 27: 0.69414365, 28: 0.70688421,
    29: 0.71939909, 30: 0.7317, 31: 0.73776948, 32: 0.74378943,
    33: 0.74976104, 34: 0.75568551, 35: 0.76156384, 36: 0.76739717,
    37: 0.7731865, 38: 0.77893275, 39: 0.78463697, 40: 0.79030001,
    41: 0.79530001, 42: 0.8003, 43: 0.8053, 44: 0.81029999,
    45: 0.81529999, 46: 0.8203, 47: 0.8253, 48: 0.83029999,
    49: 0.8353, 50: 0.84029999, 51: 0.84384999  # Buddy Boost Level
}

In [65]:
cleaned_df.show(1)

+-----+-------------+-------+-----+-------------+---------+------+-------+-------------+---------+------------+------+-------+------------+---------+-------------------+-----+----+------+-------+----+
|   ID|         Name|  Type1|Type2|CP Multiplier|Fast Move|FPower|  FType|FEnergy boost|FDuration|Charged Move|CPower|  CType|CEnergy cost|CDuration|Damage window start|Level|  CP|Attack|Defense|  HP|
+-----+-------------+-------+-----+-------------+---------+------+-------+-------------+---------+------------+------+-------+------------+---------+-------------------+-----+----+------+-------+----+
|150.0|Shadow Mewtwo|Psychic| NULL|        0.094|Confusion|  20.0|Psychic|         15.0|      1.6|   Psystrike|  90.0|Psychic|        50.0|      2.3|                1.0| NULL|NULL|  NULL|   NULL|NULL|
+-----+-------------+-------+-----+-------------+---------+------+-------+-------------+---------+------------+------+-------+------------+---------+-------------------+-----+----+------+-------+----+
only showing top 1 row

In [66]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import udf, col
from pyspark.sql.types import DoubleType, IntegerType
import math

In [67]:
# Broadcast the CPM values for efficient lookup within the UDF
cpm_values_broadcast = spark.sparkContext.broadcast(cpm_values)

# UDF to replace NULL in 'CP Multiplier' based on 'Level'
def fill_cpm(level, cpm):
    if cpm is None:  # Check if 'CP Multiplier' is NULL
        return cpm_values_broadcast.value.get(int(level), None)  # Replace with value from cpm_values
    else:
        return cpm

# Register the UDF
fill_cpm_udf = udf(fill_cpm, DoubleType())

# Assuming 'cleaned_df' is the DataFrame to be processed
# First, ensure 'Level' is treated as integer for key matching
cleaned_df = cleaned_df.withColumn("Level", col("Level").cast(IntegerType()))

# Apply the UDF to fill NULL values in 'CP Multiplier'
cleaned_df = cleaned_df.withColumn('CP Multiplier', fill_cpm_udf(col('Level'), col('CP Multiplier')))

In [68]:
# Assuming 'spark_df' is your Spark DataFrame
shadow_mewtwo_df = cleaned_df.filter(col("Name") == "Shadow Mewtwo")

# Convert the filtered Spark DataFrame to a Pandas DataFrame
shadow_mewtwo_pd_df = shadow_mewtwo_df.toPandas()

# Display the DataFrame to inspect "Shadow Mewtwo" data
shadow_mewtwo_pd_df.head(5)

      ID           Name    Type1 Type2  CP Multiplier  Fast Move  FPower    FType  FEnergy boost  FDuration Charged Move  CPower    CType  CEnergy cost  CDuration  Damage window start  Level  CP  Attack  Defense  HP
0  150.0  Shadow Mewtwo  Psychic  None       0.094000  Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0    NaN NaN     NaN      NaN NaN
1  150.0  Shadow Mewtwo  Psychic  None       0.166398  Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0    NaN NaN     NaN      NaN NaN
2  150.0  Shadow Mewtwo  Psychic  None       0.215732  Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0    NaN NaN     NaN      NaN NaN
3  150.0  Shadow Mewtwo  Psychic  None       0.255720  Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0    NaN NaN     NaN      NaN NaN
4  150.0  Shadow Mewtwo  Psychic  None       0.290250  Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0    NaN NaN     NaN      NaN NaN

In [69]:
# Assuming 'spark_df' is your Spark DataFrame
palkia_origin_pd_df = cleaned_df.filter(col("Name") == "Palkia Origin Forme")

# Convert the filtered Spark DataFrame to a Pandas DataFrame
palkia_origin_pd_df = palkia_origin_pd_df.toPandas()

# Display the DataFrame to inspect "Palkia Origin Forme" data
palkia_origin_pd_df.head(5)

   ID                 Name  Type1   Type2  CP Multiplier Fast Move  FPower FType  FEnergy boost  FDuration Charged Move  CPower CType  CEnergy cost  CDuration  Damage window start  Level     CP  Attack  Defense     HP
0 NaN  Palkia Origin Forme  Water  Dragon       0.094000      None     NaN  None            NaN        NaN         None     NaN  None           NaN        NaN                  NaN      1   58.0   286.0    223.0  189.0
1 NaN  Palkia Origin Forme  Water  Dragon       0.166398      None     NaN  None            NaN        NaN         None     NaN  None           NaN        NaN                  NaN      2  183.0   286.0    223.0  189.0
2 NaN  Palkia Origin Forme  Water  Dragon       0.215732      None     NaN  None            NaN        NaN         None     NaN  None           NaN        NaN                  NaN      3  308.0   286.0    223.0  189.0
3 NaN  Palkia Origin Forme  Water  Dragon       0.255720      None     NaN  None            NaN        NaN         None     NaN  None           NaN        NaN                  NaN      4  433.0   286.0    223.0  189.0
4 NaN  Palkia Origin Forme  Water  Dragon       0.290250      None     NaN  None            NaN        NaN         None     NaN  None           NaN        NaN                  NaN      5  558.0   286.0    223.0  189.0

In [70]:
# Assuming 'spark_df' is your Spark DataFrame
rayquaza_pd_df = cleaned_df.filter(col("Name") == "Rayquaza")

# Convert the filtered Spark DataFrame to a Pandas DataFrame
rayquaza_pd_df = rayquaza_pd_df.toPandas()

# Display the DataFrame to inspect "Palkia Origin Forme" data
rayquaza_pd_df.head(5)

      ID      Name   Type1   Type2  CP Multiplier    Fast Move  FPower   FType  FEnergy boost  FDuration   Charged Move  CPower   CType  CEnergy cost  CDuration  Damage window start  Level     CP  Attack  Defense     HP
0  384.0  Rayquaza  Dragon  Flying          0.094  Dragon Tail    15.0  Dragon            9.0        1.1  Dragon Ascent   140.0  Flying          50.0        3.5                  3.2      1   54.0   284.0    170.0  213.0
1  384.0  Rayquaza  Dragon  Flying          0.094  Dragon Tail    15.0  Dragon            9.0        1.1  Dragon Ascent   140.0  Flying          50.0        3.5                  3.2      2  170.0   284.0    170.0  213.0
2  384.0  Rayquaza  Dragon  Flying          0.094  Dragon Tail    15.0  Dragon            9.0        1.1  Dragon Ascent   140.0  Flying          50.0        3.5                  3.2      3  285.0   284.0    170.0  213.0
3  384.0  Rayquaza  Dragon  Flying          0.094  Dragon Tail    15.0  Dragon            9.0        1.1  Dragon Ascent   140.0  Flying          50.0        3.5                  3.2      4  401.0   284.0    170.0  213.0
4  384.0  Rayquaza  Dragon  Flying          0.094  Dragon Tail    15.0  Dragon            9.0        1.1  Dragon Ascent   140.0  Flying          50.0        3.5                  3.2      5  517.0   284.0    170.0  213.0

In [71]:
shadow_mewtwo_pd_df.to_csv('shadow_mewtwo.csv')

In [72]:
pokemon_details_df = pd.read_csv('extracted_data/Pokemon_GO_Details.csv')

In [73]:
pokemon_details_df.rename(columns={'Pokemon Go': 'Name'}, inplace=True)

In [74]:
shadow_m2_test = shadow_mewtwo_pd_df

In [75]:
merged_df = shadow_m2_test.merge(pokemon_details_df, on='Name', how='left')

In [76]:
merged_df

         ID_x           Name  Type1_x Type2_x  CP Multiplier_x Fast Move_x  FPower_x  FType_x  FEnergy boost_x  FDuration_x Charged Move_x  CPower_x  CType_x  CEnergy cost_x  CDuration_x  Damage window start_x  Level_x  CP_x  Attack_x  Defense_x  HP_x   ID_y  Type1_y Type2_y   HP_y  Attack_y  Defense_y  Level_y  CP Multiplier_y  CP_y Fast Move_y  FPower_y  FType_y  FEnergy boost_y  FDuration_y Charged Move_y  CPower_y  CType_y  CEnergy cost_y  CDuration_y  Damage window start_y
0       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0      NaN   NaN       NaN        NaN   NaN  150.0  Psychic     NaN   21.0      35.0       15.0        1         0.094000    59   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0
1       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0      NaN   NaN       NaN        NaN   NaN  150.0  Psychic     NaN   38.0      62.0       27.0        2         0.166398   185   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0
2       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0      NaN   NaN       NaN        NaN   NaN  150.0  Psychic     NaN   49.0      80.0       35.0        3         0.215732   311   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0
3       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0      NaN   NaN       NaN        NaN   NaN  150.0  Psychic     NaN   58.0      95.0       42.0        4         0.255720   437   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0
4       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0      NaN   NaN       NaN        NaN   NaN  150.0  Psychic     NaN   66.0     108.0       48.0        5         0.290250   563   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0
...       ...            ...      ...     ...              ...         ...       ...      ...              ...          ...            ...       ...      ...             ...          ...                    ...      ...   ...       ...        ...   ...    ...      ...     ...    ...       ...        ...      ...              ...   ...         ...       ...      ...              ...          ...            ...       ...      ...             ...          ...                    ...
842719  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0      NaN   NaN       NaN        NaN   NaN  150.0  Psychic     NaN  188.0     309.0      137.0       47         0.825300  4557  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0
842720  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0      NaN   NaN       NaN        NaN   NaN  150.0  Psychic     NaN  190.0     311.0      138.0       48         0.830300  4612  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0
842721  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0      NaN   NaN       NaN        NaN   NaN  150.0  Psychic     NaN  191.0     313.0      139.0       49         0.835300  4668  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0
842722  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0      NaN   NaN       NaN        NaN   NaN  150.0  Psychic     NaN  192.0     315.0      140.0       50         0.840300  4724  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0
842723  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0      NaN   NaN       NaN        NaN   NaN  150.0  Psychic     NaN  193.0     316.0      140.0       51         0.845300  4780  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0

[842724 rows x 41 columns]

In [77]:
columns_to_drop = ['Level_x', 'CP_x', 'Attack_x', 'Defense_x', 'HP_x']

# Drop the specified columns
merged_df.drop(columns=columns_to_drop, inplace=True)

In [78]:
merged_df

         ID_x           Name  Type1_x Type2_x  CP Multiplier_x Fast Move_x  FPower_x  FType_x  FEnergy boost_x  FDuration_x Charged Move_x  CPower_x  CType_x  CEnergy cost_x  CDuration_x  Damage window start_x   ID_y  Type1_y Type2_y   HP_y  Attack_y  Defense_y  Level_y  CP Multiplier_y  CP_y Fast Move_y  FPower_y  FType_y  FEnergy boost_y  FDuration_y Charged Move_y  CPower_y  CType_y  CEnergy cost_y  CDuration_y  Damage window start_y
0       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0  150.0  Psychic     NaN   21.0      35.0       15.0        1         0.094000    59   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0
1       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0  150.0  Psychic     NaN   38.0      62.0       27.0        2         0.166398   185   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0
2       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0  150.0  Psychic     NaN   49.0      80.0       35.0        3         0.215732   311   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0
3       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0  150.0  Psychic     NaN   58.0      95.0       42.0        4         0.255720   437   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0
4       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0  150.0  Psychic     NaN   66.0     108.0       48.0        5         0.290250   563   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0
...       ...            ...      ...     ...              ...         ...       ...      ...              ...          ...            ...       ...      ...             ...          ...                    ...    ...      ...     ...    ...       ...        ...      ...              ...   ...         ...       ...      ...              ...          ...            ...       ...      ...             ...          ...                    ...
842719  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0  150.0  Psychic     NaN  188.0     309.0      137.0       47         0.825300  4557  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0
842720  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0  150.0  Psychic     NaN  190.0     311.0      138.0       48         0.830300  4612  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0
842721  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0  150.0  Psychic     NaN  191.0     313.0      139.0       49         0.835300  4668  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0
842722  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0  150.0  Psychic     NaN  192.0     315.0      140.0       50         0.840300  4724  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0
842723  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0  150.0  Psychic     NaN  193.0     316.0      140.0       51         0.845300  4780  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0

[842724 rows x 36 columns]

In [79]:
# Additional columns to drop
additional_columns_to_drop = [
    'ID_y', 'Type1_y', 'Type2_y', 'CP Multiplier_y',
    'Fast Move_y', 'FPower_y', 'FType_y', 'FEnergy boost_y', 'FDuration_y',
    'Charged Move_y', 'CPower_y', 'CType_y', 'CEnergy cost_y', 'CDuration_y', 'Damage window start_y'
]

# Drop the additional specified columns
merged_df.drop(columns=additional_columns_to_drop, inplace=True)

merged_df

         ID_x           Name  Type1_x Type2_x  CP Multiplier_x Fast Move_x  FPower_x  FType_x  FEnergy boost_x  FDuration_x Charged Move_x  CPower_x  CType_x  CEnergy cost_x  CDuration_x  Damage window start_x   HP_y  Attack_y  Defense_y  Level_y  CP_y
0       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0   21.0      35.0       15.0        1    59
1       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0   38.0      62.0       27.0        2   185
2       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0   49.0      80.0       35.0        3   311
3       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0   58.0      95.0       42.0        4   437
4       150.0  Shadow Mewtwo  Psychic    None           0.0940   Confusion      20.0  Psychic             15.0          1.6      Psystrike      90.0  Psychic            50.0          2.3                    1.0   66.0     108.0       48.0        5   563
...       ...            ...      ...     ...              ...         ...       ...      ...              ...          ...            ...       ...      ...             ...          ...                    ...    ...       ...        ...      ...   ...
842719  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0  188.0     309.0      137.0       47  4557
842720  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0  190.0     311.0      138.0       48  4612
842721  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0  191.0     313.0      139.0       49  4668
842722  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0  192.0     315.0      140.0       50  4724
842723  150.0  Shadow Mewtwo  Psychic    None           0.8453  Psycho Cut       5.0  Psychic              8.0          0.6    Frustration      10.0   Normal            33.0          2.0                    1.0  193.0     316.0      140.0       51  4780

[842724 rows x 21 columns]

In [80]:
merged_df.columns = merged_df.columns.str.replace('_x', '').str.replace('_y', '')
merged_df

           ID           Name    Type1 Type2  CP Multiplier   Fast Move  FPower    FType  FEnergy boost  FDuration Charged Move  CPower    CType  CEnergy cost  CDuration  Damage window start     HP  Attack  Defense  Level    CP
0       150.0  Shadow Mewtwo  Psychic  None         0.0940   Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0   21.0    35.0     15.0      1    59
1       150.0  Shadow Mewtwo  Psychic  None         0.0940   Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0   38.0    62.0     27.0      2   185
2       150.0  Shadow Mewtwo  Psychic  None         0.0940   Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0   49.0    80.0     35.0      3   311
3       150.0  Shadow Mewtwo  Psychic  None         0.0940   Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0   58.0    95.0     42.0      4   437
4       150.0  Shadow Mewtwo  Psychic  None         0.0940   Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0   66.0   108.0     48.0      5   563
...       ...            ...      ...   ...            ...         ...     ...      ...            ...        ...          ...     ...      ...           ...        ...                  ...    ...     ...      ...    ...   ...
842719  150.0  Shadow Mewtwo  Psychic  None         0.8453  Psycho Cut     5.0  Psychic            8.0        0.6  Frustration    10.0   Normal          33.0        2.0                  1.0  188.0   309.0    137.0     47  4557
842720  150.0  Shadow Mewtwo  Psychic  None         0.8453  Psycho Cut     5.0  Psychic            8.0        0.6  Frustration    10.0   Normal          33.0        2.0                  1.0  190.0   311.0    138.0     48  4612
842721  150.0  Shadow Mewtwo  Psychic  None         0.8453  Psycho Cut     5.0  Psychic            8.0        0.6  Frustration    10.0   Normal          33.0        2.0                  1.0  191.0   313.0    139.0     49  4668
842722  150.0  Shadow Mewtwo  Psychic  None         0.8453  Psycho Cut     5.0  Psychic            8.0        0.6  Frustration    10.0   Normal          33.0        2.0                  1.0  192.0   315.0    140.0     50  4724
842723  150.0  Shadow Mewtwo  Psychic  None         0.8453  Psycho Cut     5.0  Psychic            8.0        0.6  Frustration    10.0   Normal          33.0        2.0                  1.0  193.0   316.0    140.0     51  4780

[842724 rows x 21 columns]

In [81]:
rayquaza_pd_df.columns

Index(['ID', 'Name', 'Type1', 'Type2', 'CP Multiplier', 'Fast Move', 'FPower', 'FType', 'FEnergy boost', 'FDuration', 'Charged Move', 'CPower', 'CType', 'CEnergy cost', 'CDuration', 'Damage window start', 'Level', 'CP', 'Attack', 'Defense', 'HP'], dtype='object')

In [82]:
merged_df = merged_df[['ID', 'Name', 'Type1', 'Type2', 'CP Multiplier', 'Fast Move', 'FPower', 'FType', 'FEnergy boost', 'FDuration', 'Charged Move', 'CPower', 'CType', 'CEnergy cost', 'CDuration', 'Damage window start', 'Level', 'CP', 'Attack', 'Defense', 'HP']]

In [83]:
merged_df

           ID           Name    Type1 Type2  CP Multiplier   Fast Move  FPower    FType  FEnergy boost  FDuration Charged Move  CPower    CType  CEnergy cost  CDuration  Damage window start  Level    CP  Attack  Defense     HP
0       150.0  Shadow Mewtwo  Psychic  None         0.0940   Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0      1    59    35.0     15.0   21.0
1       150.0  Shadow Mewtwo  Psychic  None         0.0940   Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0      2   185    62.0     27.0   38.0
2       150.0  Shadow Mewtwo  Psychic  None         0.0940   Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0      3   311    80.0     35.0   49.0
3       150.0  Shadow Mewtwo  Psychic  None         0.0940   Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0      4   437    95.0     42.0   58.0
4       150.0  Shadow Mewtwo  Psychic  None         0.0940   Confusion    20.0  Psychic           15.0        1.6    Psystrike    90.0  Psychic          50.0        2.3                  1.0      5   563   108.0     48.0   66.0
...       ...            ...      ...   ...            ...         ...     ...      ...            ...        ...          ...     ...      ...           ...        ...                  ...    ...   ...     ...      ...    ...
842719  150.0  Shadow Mewtwo  Psychic  None         0.8453  Psycho Cut     5.0  Psychic            8.0        0.6  Frustration    10.0   Normal          33.0        2.0                  1.0     47  4557   309.0    137.0  188.0
842720  150.0  Shadow Mewtwo  Psychic  None         0.8453  Psycho Cut     5.0  Psychic            8.0        0.6  Frustration    10.0   Normal          33.0        2.0                  1.0     48  4612   311.0    138.0  190.0
842721  150.0  Shadow Mewtwo  Psychic  None         0.8453  Psycho Cut     5.0  Psychic            8.0        0.6  Frustration    10.0   Normal          33.0        2.0                  1.0     49  4668   313.0    139.0  191.0
842722  150.0  Shadow Mewtwo  Psychic  None         0.8453  Psycho Cut     5.0  Psychic            8.0        0.6  Frustration    10.0   Normal          33.0        2.0                  1.0     50  4724   315.0    140.0  192.0
842723  150.0  Shadow Mewtwo  Psychic  None         0.8453  Psycho Cut     5.0  Psychic            8.0        0.6  Frustration    10.0   Normal          33.0        2.0                  1.0     51  4780   316.0    140.0  193.0

[842724 rows x 21 columns]

In [84]:
cleaned_df.count()

22132419

In [ ]:
from pyspark.sql import SparkSession

# Assuming `spark` is your SparkSession and `cleaned_df` is already loaded as a Spark DataFrame
# `pokemon_details_df` is a pandas DataFrame with renamed columns

# Convert pokemon names to a pandas Series for intersection
cleaned_pokemon_names = cleaned_df.select("Name").distinct().toPandas()["Name"]
details_pokemon_names = pokemon_details_df["Name"]

# Find common Pokemon names
common_pokemon_names = pd.Series(list(set(cleaned_pokemon_names) & set(details_pokemon_names)))

# Initialize an empty pandas DataFrame for aggregation
aggregated_pandas_df = pd.DataFrame()

for name in common_pokemon_names:
    # Filter cleaned_df for the current Pokemon and convert to pandas
    subset_pandas_df = cleaned_df.filter(cleaned_df.Name == name).toPandas()
    
    # Merge with pokemon_details_df in pandas
    merged_pandas_df = subset_pandas_df.merge(pokemon_details_df, on="Name", how="left")
    
    # Perform column dropping and renaming in pandas
    columns_to_drop = [
        'Level_x', 'CP_x', 'Attack_x', 'Defense_x', 'HP_x',
        'ID_y', 'Type1_y', 'Type2_y', 'CP Multiplier_y', 'Fast Move_y', 'FPower_y', 'FType_y', 'FEnergy boost_y', 'FDuration_y',
        'Charged Move_y', 'CPower_y', 'CType_y', 'CEnergy cost_y', 'CDuration_y', 'Damage window start_y'
    ]
    merged_pandas_df.drop(columns=columns_to_drop, inplace=True)
    merged_pandas_df.columns = merged_pandas_df.columns.str.replace('_x', '').str.replace('_y', '')
    
    # Specify the column order if necessary, similar to the order listed previously
    # merged_pandas_df = merged_pandas_df[ordered_columns]
    
    # Append to the aggregated DataFrame
    aggregated_pandas_df = pd.concat([aggregated_pandas_df, merged_pandas_df], ignore_index=True)

# At this point, aggregated_pandas_df contains all processed Pok√©mon entries